import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
// import styles from '@/styles/Home.module.css'
import { Box, Button, Flex, Heading, HStack, SimpleGrid } from '@chakra-ui/react'

import stle from '../stles/menu.module.css'
import React from 'react'
import { Homebox } from '@/component/home/homecom'
import CaptionCarousel from '@/component/home/carousel'
import { Offerdiv } from '@/component/home/offer'
import { ChevronLeftIcon, ChevronRightIcon } from '@chakra-ui/icons'
const inter = Inter({ subsets: ['latin'] })
import { useLocation, useNavigate } from "react-router-dom";
import {useEffect}from "react"
export default function Home() {

  const lefttoright=()=>{
  let left : any=  document.getElementById("container")
    left.scrollLeft-=40 
  }
  const righttoleft=()=>{
    let right :HTMLElement | null|any=document.getElementById("container")
    right.scrollLeft+=40
  }
  return (
    <>
      <Head>
        <title>KFC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Box marginTop={'80px'}>
          <Box h='80px'bg='#FFF5F5'display={'flex'} alignItems={'center'}justifyContent={{lg:'flex-start',md:"center",sm:"center"}}>
          <Heading marginLeft={'20px'}>WELCOME TO KFC!</Heading>
          </Box>

            <CaptionCarousel/>
          <Box  marginTop={'80px'}>
            <Box w={'80%'}margin='auto'>
            <Heading marginBottom='20px'>BROWSE CATEGORIES</Heading>
            <SimpleGrid gap={'10px'} columns={{lg:3,md:2,sm:2}}>
              <Homebox title={"EXCLUSIVE DEAL"} src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/categories/CAT208.jpg?ver=26.25'/>
              <Homebox title={"CHIZZA"} src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/categories/CAT212.jpg?ver=26.25'/>
              <Homebox title={"CHICKEN BUCKETS"} src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/categories/CAT86.jpg?ver=26.25'/>
              <Homebox title={"NEW LAUNCH"} src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/categories/CAT200.jpg?ver=26.25'/>
              <Homebox title={"BIRYANI BUCKETS"} src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/categories/CAT190.jpg?ver=26.25'/>
              <Homebox title={"BURGERS"} src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/categories/CAT99.jpg?ver=26.25'/>
              <Homebox title={"SNACKS"} src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/categories/CAT89.jpg?ver=26.25'/>
              </SimpleGrid> </Box>
          </Box>

          {/* <div style={{marginLeft:'60px' ,border:"1px solid red",overflow:"scroll"}}  > */}
          <Box position={'relative'}>
          <HStack className={stle.scrollbar}  id='container' overflow={'scroll'}  margin={{lg:'40px 0 20px 100px',md:"40px 0 20px 80px",sm:"40px 0 20px auto"}}  >
            <Flex gap='20px' >

           <Offerdiv  src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/offers/md/CHKZINGER.jpg?ver=26.39' />
           <Offerdiv  src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/offers/md/ADDCHK99.jpg?ver=26.39' />
           <Offerdiv  src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/offers/xl/BIGSAVE.jpg?ver=26.39' />
           <Offerdiv  src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/offers/xl/VEGZINGER.jpg?ver=26.39' />
           <Offerdiv  src='https://orderserv-kfc-assets.yum.com/15895bb59f7b4bb588ee933f8cd5344a/images/offers/md/CHKZINGER.jpg?ver=26.39' />
            </Flex>
        </HStack>
        <Button top='40%'left={'7px'} position={'absolute'} onClick={lefttoright} bg='none' fontSize={'6xl'}><ChevronLeftIcon/> </Button>
        <Button top={'40%'} right='0px'position={'absolute'} onClick={righttoleft}bg='none' fontSize={'6xl'}><ChevronRightIcon/> </Button>
        </Box>
          </Box>
      </main>
    </>
  )
}

